name: RamCore
version: '1.0.0-SNAPSHOT'
main: dev.willram.ramcore.RamCore
api-version: '26.1.2'
folia-supported: true
dependencies:
  server:
    ProtocolLib:
      load: BEFORE
      required: false
      # This means that your plugin will not have access to their classpath
      join-classpath: true
permissions:
  ramcore.diagnostics:
    description: Allows use of RamCore diagnostic commands.
    default: op
